# host-address-subnets-union-service
Сервис сопоставления адресов хостов и подсетей

# Поток данных:
1. Клиент: input.txt → список адресов
2. Клиент: список → Protobuf сериализация
3. Клиент: отправка в RabbitMQ (queue: match_requests)
4. Сервер: получение из RabbitMQ
5. Сервер: десериализация Protobuf
6. Сервер: разделение на hosts/subnets
7. Сервер: поиск соответствий (Longest Prefix Match)
8. Сервер: формирование ответа
9. Сервер: сериализация → отправка в RabbitMQ (queue: match_responses)
10. Клиент: получение → десериализация
11. Клиент: запись в output.txt

# Запуск и проверка
1. docker-compose up --build
2. docker exec -it ip-matcher-client /bin/bash
3. python client.py input.txt output.txt
4. cat output.txt

# Доп задание с выходными данными
Для реализации бизнес логики использовал библиотеку ipaddress, она в свою очередь возвращает объект типа IPv4Network или IPv6Network, в зависимости от типа адреса. Т.е. если при выключеном strict=False позволяет передавать любой IP-адрес внутри диапазона подсети и в этом случае, даже если указанный IP-адрес не является адресом сети, функция всё равно создаст объект сети, интерпретируя его как часть этой подсети. соответсвенно выходные данные получались следуюущие:
1.1.1.1 - 0
3fff::5e8c:32 - 0
2001:3:28:45:3f:de:3:64 - 2001:3::/24
5.4.2.1 - 0
135.6.11.28 - 135.6.8.0/17
135.6.14.33 - 135.6.14.0/24
Такие же как в примере

Но если мы укажем strict=False, который будет требовать, чтобы указанный IP-адрес был адресом сети — то есть, соответствовал началу диапазона подсети и если передавать IP-адрес, который не является адресом сети, вызов вызовет ошибку ValueError(есть обработчик). То мы получаем следующие данные 
1.1.1.1 - 0
3fff::5e8c:32 - 0
2001:3:28:45:3f:de:3:64 - 0
5.4.2.1 - 0
135.6.11.28 - 0
135.6.14.33 - 135.6.14.0/24
Является ли это обноружением ошибки?
